extends RefCounted
## The game's mix, and the plumbing every sound goes through to reach it.
##
## The counterpart to particle_kit.gd: that file knows how an effect looks, this one knows how
## it sounds. Neither knows anything about a particular spell or weapon — the effects supply
## the clips and the tuning (see weapon_sfx.gd, firebolt_projectile.gd).
##
## --- The buses ---
##
## Defined in res://default_bus_layout.tres, which Godot loads on its own: that path is the
## default value of the audio/buses/default_bus_layout project setting, so nothing in
## project.godot points at it. The file is REGENERATED by the editor's Audio panel the moment
## anyone drags a fader, so it holds no comments — this doc block is the layout's real home.
##
##   Master        everything, and the only place a global volume belongs
##   └─ SFX        the world: spells, blades, footsteps, doors
##
## SFX exists so one slider can duck the game world without touching music or menu clicks, and
## so a compressor or a dungeon reverb can later sit on the world's sound alone. When music and
## UI arrive (there is a synthwave bundle and a button library waiting in _sound/), add them as
## siblings sending to "Master" — NOT into SFX, or the SFX slider drags them down with it.

## The world bus. Every diegetic sound sets this; music and UI will want their own.
const BUS_SFX := "SFX"

# --- The arena's audio scale -----------------------------------------------
# One place for how far sound carries, so a spell and a sword agree about it. Both numbers are
# set by the orbit camera rather than by the room: it sits 16 m from the pivot by default and
# pulls back to 35 (camera_controller.gd), and the camera is the listener.

## Metres of full-strength radius. Comfortably past the default camera distance, so zooming out
## does not fade the fight simply because the player wanted to see more of it.
const UNIT_SIZE := 25.0
## Past this a source is silent — beyond the camera's own limit, so the cutoff is for sound
## elsewhere in the dungeon rather than something the player can hear happening.
const MAX_DISTANCE := 60.0

## Default one-shot lifetime when a stream will not report its own length. Longer than any clip
## in assets/audio, because the cost of guessing high is a silent node lingering for a moment
## and the cost of guessing low is a sound cut off mid-swing.
const FALLBACK_LENGTH := 3.0


static func route(player: Node, bus: String = BUS_SFX) -> void:
	## Point an AudioStreamPlayer / 2D / 3D at `bus`, or leave it on Master if that bus is not
	## in the layout.
	##
	## The check is the whole reason this is a function. Assigning a bus name Godot does not
	## know is not a quiet no-op — it errors on assignment and again on every play(), so a
	## layout file that failed to load or got rewritten in the editor would turn one missing
	## bus into a console full of red. Falling back to Master keeps the sound audible and the
	## problem to a single warning.
	if AudioServer.get_bus_index(bus) == -1:
		push_warning("Audio bus '%s' missing from the layout; playing on Master." % bus)
		return
	player.bus = bus


static func configure(player: AudioStreamPlayer3D, volume_db: float = 0.0) -> void:
	## Apply the arena's audio scale and put the player on the world bus. Anything that builds
	## its own AudioStreamPlayer3D should come through here, so there is one answer to "how far
	## does this carry" rather than one per effect.
	player.volume_db = volume_db
	player.unit_size = UNIT_SIZE
	player.max_distance = MAX_DISTANCE
	route(player)


static func one_shot(parent: Node, at: Vector3, clip: String, volume_db: float = 0.0,
		pitch_jitter: float = 0.0) -> void:
	## Play `clip` once at a point in the world and clean up after itself.
	##
	## Parented to the arena rather than to whoever caused the sound: a blow that kills its
	## target must still be heard, and a sound hung off a corpse dies with it.
	##
	## `pitch_jitter` is a fraction — 0.06 means ±6%. Melee leans on it hard, because three
	## sword clips at a fixed pitch turn into a metronome within one fight.
	if parent == null or not parent.is_inside_tree():
		return
	var stream := load(clip) as AudioStream
	if stream == null:
		push_warning("SFX missing: " + clip)
		return

	var player := AudioStreamPlayer3D.new()
	player.name = "OneShot"
	player.stream = stream
	configure(player, volume_db)
	if pitch_jitter > 0.0:
		player.pitch_scale = randf_range(1.0 - pitch_jitter, 1.0 + pitch_jitter)
	parent.add_child(player)
	player.global_position = at
	player.play()

	# Freed on a measured timer rather than on `finished`: a clip that came in looping would
	# never emit that signal, and a node that never frees is a leak on every single swing.
	# Pitching a clip down stretches it, so the wait is divided by the pitch actually used.
	var length: float = stream.get_length()
	if length <= 0.0:
		length = FALLBACK_LENGTH
	await parent.get_tree().create_timer(length / player.pitch_scale + 0.1).timeout
	if is_instance_valid(player):
		player.queue_free()


static func pick(clips: Array) -> String:
	## One clip at random from a variation set. Returns "" for an empty set, which one_shot
	## treats as a missing clip rather than crashing mid-fight.
	if clips.is_empty():
		return ""
	return clips[randi() % clips.size()]
